package ccnop

const moduleFileTpl = `// Code generated by protoc-gen-validate
// source: {{ .InputPath }}
// DO NOT EDIT!!!

#include "{{ output .File ".validate.h" }}"

namespace pgv {
namespace validate {
using std::string;

{{ range .AllMessages }}
{{- if not (ignored .) -}}
{{- if not (disabled .) -}}
pgv::Validator<{{ class . }}> {{ staticVarName . }}(static_cast<bool(*)(const {{ class .}}&, pgv::ValidationMsg*)>({{ package .}}::Validate));
{{- end -}}
{{ end }}
{{ end }}

} // namespace validate
} // namespace pgv

{{ range .Package.ProtoName.Split }}
namespace {{ . }} {
{{- end }}

{{ range .AllMessages }}
	inline bool Validate(__attribute__((unused)) const {{ class . }}& m, __attribute__((unused)) pgv::ValidationMsg* err) {
		return true;
	}
{{ end }}

{{ range .Package.ProtoName.Split -}}
} // namespace
{{ end }}
`
