version: 2
builds:
  - main: .
    id: "protoc-gen-validate"
    binary: "protoc-gen-validate"
    env:
      - CGO_ENABLED=0
  - main: ./cmd/protoc-gen-validate-cpp
    id: "protoc-gen-validate-cpp"
    binary: "protoc-gen-validate-cpp"
    env:
      - CGO_ENABLED=0
  - main: ./cmd/protoc-gen-validate-go
    id: "protoc-gen-validate-go"
    binary: "protoc-gen-validate-go"
    env:
      - CGO_ENABLED=0
  - main: ./cmd/protoc-gen-validate-java
    id: "protoc-gen-validate-java"
    binary: "protoc-gen-validate-java"
    env:
      - CGO_ENABLED=0
