#! /usr/bin/python3

"""
There's two sets of python requirements to discuss. The ones specified in requirements.txt are installed
during the Docker build and are used for linting, building, and uploading the PGV python package to PyPI.

The other set is in the install_requires section of setup.cfg. These are needed to actually use the package, and
of course for our testing as well.

We use the pip_install rule of @rules_python to install these packages. Unfortunately:
- the rule can't handle setup.cfg directly, it wants a file in simple requirements.txt format
- as a repository_rule, it won't handle generated files so we can't write a genrule to create
  a requirements.txt out of setup.cfg.

So, in an effort to keep the setup.cfg the source-of-truth for what packages are installed to execute the test
harness, this script converts the install_requires section of setup.cfg into a file pip_install will handle.
"""

import configparser

config = configparser.ConfigParser()
config.read('python/setup.cfg')

with open('python/requirements.generated', 'w') as req:
    req.write("# Auto-generated by requirements_parser.py")
    req.write(config['options']['install_requires'])
