package python

const fileTpl = `
#-*- coding: utf-8 -*-
#Code generated by protoc-gen-validate. DO NOT EDIT
import datetime
import struct
import re

from google.protobuf.timestamp_pb2 import Timestamp
from google.protobuf.duration_pb2 import Duration

from google.protobuf.internal import enum_type_wrapper

EMPTY_TIMESTAMP = Timestamp()
EMPTY_DURATION = Duration()

def unicode_len(s):
	try:
		return len(s.decode('utf-8'))
	except:
		return len(s)

def byte_length(s):
	try:
		return len(s.encode('utf-8'))
	except:
		return len(s)

from {{ output .File }} import *

{{ range $p := enumPackages (externalEnums .) }}
from {{ $p }} import *
{{ end }}

{{ range .AllMessages }}
	{{- template "msg" . }}
{{ end }}
`
