// Code generated by protoc-gen-validate
// source: any.proto
// DO NOT EDIT!!!

package tests_kitchensink

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/gogo/protobuf/types"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)

	_ = types.DynamicAny{}
)

// Validate checks the field values on Any with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Any) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetNone()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AnyValidationError{
				Field:  "None",
				Reason: "embedded message failed validation",
				Cause:  err,
			}
		}
	}

	if m.GetRequired() == nil {
		return AnyValidationError{
			Field:  "Required",
			Reason: "value is required",
		}
	}

	if a := m.GetRequired(); a != nil {

	}

	if a := m.GetIn(); a != nil {

		if _, ok := _Any_In_InLookup[a.GetTypeUrl()]; !ok {
			return AnyValidationError{
				Field:  "In",
				Reason: "type URL must be in list [foo bar]",
			}
		}

	}

	if a := m.GetNotIn(); a != nil {

		if _, ok := _Any_NotIn_NotInLookup[a.GetTypeUrl()]; ok {
			return AnyValidationError{
				Field:  "NotIn",
				Reason: "type URL must not be in list [fizz buzz]",
			}
		}

	}

	return nil
}

// AnyValidationError is the validation error returned by Any.Validate if the
// designated constraints aren't met.
type AnyValidationError struct {
	Field  string
	Reason string
	Cause  error
	Key    bool
}

// Error satisfies the builtin error interface
func (e AnyValidationError) Error() string {
	cause := ""
	if e.Cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.Cause)
	}

	key := ""
	if e.Key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAny.%s: %s%s",
		key,
		e.Field,
		e.Reason,
		cause)
}

var _ error = AnyValidationError{}

var _Any_In_InLookup = map[string]struct{}{
	"foo": {},
	"bar": {},
}

var _Any_NotIn_NotInLookup = map[string]struct{}{
	"fizz": {},
	"buzz": {},
}
