// Code generated by protoc-gen-gogo.
// source: duration.proto
// DO NOT EDIT!

package tests_kitchensink

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/gogo/protobuf/types"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/gogo/protobuf/gogoproto"

import time "time"

import github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Duration struct {
	None      *google_protobuf1.Duration `protobuf:"bytes,1,opt,name=none" json:"none,omitempty"`
	Lt        *google_protobuf1.Duration `protobuf:"bytes,2,opt,name=lt" json:"lt,omitempty"`
	Lte       *google_protobuf1.Duration `protobuf:"bytes,3,opt,name=lte" json:"lte,omitempty"`
	Gt        *google_protobuf1.Duration `protobuf:"bytes,4,opt,name=gt" json:"gt,omitempty"`
	Gte       *google_protobuf1.Duration `protobuf:"bytes,5,opt,name=gte" json:"gte,omitempty"`
	LtGt      *google_protobuf1.Duration `protobuf:"bytes,6,opt,name=lt_gt,json=ltGt" json:"lt_gt,omitempty"`
	LtGte     *google_protobuf1.Duration `protobuf:"bytes,7,opt,name=lt_gte,json=ltGte" json:"lt_gte,omitempty"`
	LteGt     *google_protobuf1.Duration `protobuf:"bytes,8,opt,name=lte_gt,json=lteGt" json:"lte_gt,omitempty"`
	LteGte    *google_protobuf1.Duration `protobuf:"bytes,9,opt,name=lte_gte,json=lteGte" json:"lte_gte,omitempty"`
	LtGtInv   *google_protobuf1.Duration `protobuf:"bytes,10,opt,name=lt_gt_inv,json=ltGtInv" json:"lt_gt_inv,omitempty"`
	LtGteInv  *google_protobuf1.Duration `protobuf:"bytes,11,opt,name=lt_gte_inv,json=ltGteInv" json:"lt_gte_inv,omitempty"`
	LteGtInv  *google_protobuf1.Duration `protobuf:"bytes,12,opt,name=lte_gt_inv,json=lteGtInv" json:"lte_gt_inv,omitempty"`
	LteGteInv *google_protobuf1.Duration `protobuf:"bytes,13,opt,name=lte_gte_inv,json=lteGteInv" json:"lte_gte_inv,omitempty"`
	Required  *google_protobuf1.Duration `protobuf:"bytes,14,opt,name=required" json:"required,omitempty"`
	In        *google_protobuf1.Duration `protobuf:"bytes,15,opt,name=in" json:"in,omitempty"`
	NotIn     *google_protobuf1.Duration `protobuf:"bytes,16,opt,name=not_in,json=notIn" json:"not_in,omitempty"`
	Gogo1     *time.Duration             `protobuf:"bytes,17,opt,name=gogo1,stdduration" json:"gogo1,omitempty"`
	Gogo2     google_protobuf1.Duration  `protobuf:"bytes,18,opt,name=gogo2" json:"gogo2"`
	Gogo3     time.Duration              `protobuf:"bytes,19,opt,name=gogo3,stdduration" json:"gogo3"`
	Gogo4     google_protobuf1.Duration  `protobuf:"bytes,20,opt,name=gogo4" json:"gogo4"`
}

func (m *Duration) Reset()                    { *m = Duration{} }
func (m *Duration) String() string            { return proto.CompactTextString(m) }
func (*Duration) ProtoMessage()               {}
func (*Duration) Descriptor() ([]byte, []int) { return fileDescriptorDuration, []int{0} }

func (m *Duration) GetNone() *google_protobuf1.Duration {
	if m != nil {
		return m.None
	}
	return nil
}

func (m *Duration) GetLt() *google_protobuf1.Duration {
	if m != nil {
		return m.Lt
	}
	return nil
}

func (m *Duration) GetLte() *google_protobuf1.Duration {
	if m != nil {
		return m.Lte
	}
	return nil
}

func (m *Duration) GetGt() *google_protobuf1.Duration {
	if m != nil {
		return m.Gt
	}
	return nil
}

func (m *Duration) GetGte() *google_protobuf1.Duration {
	if m != nil {
		return m.Gte
	}
	return nil
}

func (m *Duration) GetLtGt() *google_protobuf1.Duration {
	if m != nil {
		return m.LtGt
	}
	return nil
}

func (m *Duration) GetLtGte() *google_protobuf1.Duration {
	if m != nil {
		return m.LtGte
	}
	return nil
}

func (m *Duration) GetLteGt() *google_protobuf1.Duration {
	if m != nil {
		return m.LteGt
	}
	return nil
}

func (m *Duration) GetLteGte() *google_protobuf1.Duration {
	if m != nil {
		return m.LteGte
	}
	return nil
}

func (m *Duration) GetLtGtInv() *google_protobuf1.Duration {
	if m != nil {
		return m.LtGtInv
	}
	return nil
}

func (m *Duration) GetLtGteInv() *google_protobuf1.Duration {
	if m != nil {
		return m.LtGteInv
	}
	return nil
}

func (m *Duration) GetLteGtInv() *google_protobuf1.Duration {
	if m != nil {
		return m.LteGtInv
	}
	return nil
}

func (m *Duration) GetLteGteInv() *google_protobuf1.Duration {
	if m != nil {
		return m.LteGteInv
	}
	return nil
}

func (m *Duration) GetRequired() *google_protobuf1.Duration {
	if m != nil {
		return m.Required
	}
	return nil
}

func (m *Duration) GetIn() *google_protobuf1.Duration {
	if m != nil {
		return m.In
	}
	return nil
}

func (m *Duration) GetNotIn() *google_protobuf1.Duration {
	if m != nil {
		return m.NotIn
	}
	return nil
}

func (m *Duration) GetGogo1() *time.Duration {
	if m != nil {
		return m.Gogo1
	}
	return nil
}

func (m *Duration) GetGogo2() google_protobuf1.Duration {
	if m != nil {
		return m.Gogo2
	}
	return google_protobuf1.Duration{}
}

func (m *Duration) GetGogo3() time.Duration {
	if m != nil {
		return m.Gogo3
	}
	return 0
}

func (m *Duration) GetGogo4() google_protobuf1.Duration {
	if m != nil {
		return m.Gogo4
	}
	return google_protobuf1.Duration{}
}

func init() {
	proto.RegisterType((*Duration)(nil), "tests.kitchensink.Duration")
}
func (m *Duration) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Duration) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.None != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.None.Size()))
		n1, err := m.None.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Lt != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.Lt.Size()))
		n2, err := m.Lt.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.Lte != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.Lte.Size()))
		n3, err := m.Lte.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.Gt != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.Gt.Size()))
		n4, err := m.Gt.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if m.Gte != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.Gte.Size()))
		n5, err := m.Gte.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if m.LtGt != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.LtGt.Size()))
		n6, err := m.LtGt.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if m.LtGte != nil {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.LtGte.Size()))
		n7, err := m.LtGte.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	if m.LteGt != nil {
		dAtA[i] = 0x42
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.LteGt.Size()))
		n8, err := m.LteGt.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	if m.LteGte != nil {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.LteGte.Size()))
		n9, err := m.LteGte.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n9
	}
	if m.LtGtInv != nil {
		dAtA[i] = 0x52
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.LtGtInv.Size()))
		n10, err := m.LtGtInv.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n10
	}
	if m.LtGteInv != nil {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.LtGteInv.Size()))
		n11, err := m.LtGteInv.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n11
	}
	if m.LteGtInv != nil {
		dAtA[i] = 0x62
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.LteGtInv.Size()))
		n12, err := m.LteGtInv.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n12
	}
	if m.LteGteInv != nil {
		dAtA[i] = 0x6a
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.LteGteInv.Size()))
		n13, err := m.LteGteInv.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n13
	}
	if m.Required != nil {
		dAtA[i] = 0x72
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.Required.Size()))
		n14, err := m.Required.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n14
	}
	if m.In != nil {
		dAtA[i] = 0x7a
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.In.Size()))
		n15, err := m.In.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n15
	}
	if m.NotIn != nil {
		dAtA[i] = 0x82
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintDuration(dAtA, i, uint64(m.NotIn.Size()))
		n16, err := m.NotIn.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n16
	}
	if m.Gogo1 != nil {
		dAtA[i] = 0x8a
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintDuration(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdDuration(*m.Gogo1)))
		n17, err := github_com_gogo_protobuf_types.StdDurationMarshalTo(*m.Gogo1, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n17
	}
	dAtA[i] = 0x92
	i++
	dAtA[i] = 0x1
	i++
	i = encodeVarintDuration(dAtA, i, uint64(m.Gogo2.Size()))
	n18, err := m.Gogo2.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n18
	dAtA[i] = 0x9a
	i++
	dAtA[i] = 0x1
	i++
	i = encodeVarintDuration(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdDuration(m.Gogo3)))
	n19, err := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.Gogo3, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n19
	dAtA[i] = 0xa2
	i++
	dAtA[i] = 0x1
	i++
	i = encodeVarintDuration(dAtA, i, uint64(m.Gogo4.Size()))
	n20, err := m.Gogo4.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n20
	return i, nil
}

func encodeFixed64Duration(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Duration(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintDuration(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Duration) Size() (n int) {
	var l int
	_ = l
	if m.None != nil {
		l = m.None.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.Lt != nil {
		l = m.Lt.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.Lte != nil {
		l = m.Lte.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.Gt != nil {
		l = m.Gt.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.Gte != nil {
		l = m.Gte.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.LtGt != nil {
		l = m.LtGt.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.LtGte != nil {
		l = m.LtGte.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.LteGt != nil {
		l = m.LteGt.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.LteGte != nil {
		l = m.LteGte.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.LtGtInv != nil {
		l = m.LtGtInv.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.LtGteInv != nil {
		l = m.LtGteInv.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.LteGtInv != nil {
		l = m.LteGtInv.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.LteGteInv != nil {
		l = m.LteGteInv.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.Required != nil {
		l = m.Required.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.In != nil {
		l = m.In.Size()
		n += 1 + l + sovDuration(uint64(l))
	}
	if m.NotIn != nil {
		l = m.NotIn.Size()
		n += 2 + l + sovDuration(uint64(l))
	}
	if m.Gogo1 != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdDuration(*m.Gogo1)
		n += 2 + l + sovDuration(uint64(l))
	}
	l = m.Gogo2.Size()
	n += 2 + l + sovDuration(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.Gogo3)
	n += 2 + l + sovDuration(uint64(l))
	l = m.Gogo4.Size()
	n += 2 + l + sovDuration(uint64(l))
	return n
}

func sovDuration(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozDuration(x uint64) (n int) {
	return sovDuration(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Duration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDuration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Duration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Duration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field None", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.None == nil {
				m.None = &google_protobuf1.Duration{}
			}
			if err := m.None.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Lt == nil {
				m.Lt = &google_protobuf1.Duration{}
			}
			if err := m.Lt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Lte == nil {
				m.Lte = &google_protobuf1.Duration{}
			}
			if err := m.Lte.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Gt == nil {
				m.Gt = &google_protobuf1.Duration{}
			}
			if err := m.Gt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Gte == nil {
				m.Gte = &google_protobuf1.Duration{}
			}
			if err := m.Gte.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LtGt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LtGt == nil {
				m.LtGt = &google_protobuf1.Duration{}
			}
			if err := m.LtGt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LtGte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LtGte == nil {
				m.LtGte = &google_protobuf1.Duration{}
			}
			if err := m.LtGte.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LteGt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LteGt == nil {
				m.LteGt = &google_protobuf1.Duration{}
			}
			if err := m.LteGt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LteGte", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LteGte == nil {
				m.LteGte = &google_protobuf1.Duration{}
			}
			if err := m.LteGte.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LtGtInv", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LtGtInv == nil {
				m.LtGtInv = &google_protobuf1.Duration{}
			}
			if err := m.LtGtInv.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LtGteInv", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LtGteInv == nil {
				m.LtGteInv = &google_protobuf1.Duration{}
			}
			if err := m.LtGteInv.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LteGtInv", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LteGtInv == nil {
				m.LteGtInv = &google_protobuf1.Duration{}
			}
			if err := m.LteGtInv.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LteGteInv", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LteGteInv == nil {
				m.LteGteInv = &google_protobuf1.Duration{}
			}
			if err := m.LteGteInv.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Required", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Required == nil {
				m.Required = &google_protobuf1.Duration{}
			}
			if err := m.Required.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field In", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.In == nil {
				m.In = &google_protobuf1.Duration{}
			}
			if err := m.In.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NotIn", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NotIn == nil {
				m.NotIn = &google_protobuf1.Duration{}
			}
			if err := m.NotIn.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gogo1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Gogo1 == nil {
				m.Gogo1 = new(time.Duration)
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(m.Gogo1, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gogo2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Gogo2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gogo3", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.Gogo3, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gogo4", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDuration
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Gogo4.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDuration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDuration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDuration(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDuration
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDuration
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthDuration
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowDuration
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipDuration(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthDuration = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDuration   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("duration.proto", fileDescriptorDuration) }

var fileDescriptorDuration = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x41, 0x8e, 0x12, 0x41,
	0x14, 0x86, 0xad, 0x82, 0x6e, 0x8a, 0x07, 0x32, 0x33, 0x25, 0x89, 0x35, 0x2c, 0x18, 0xc3, 0xca,
	0x90, 0xd8, 0xc4, 0xc6, 0xc4, 0xe8, 0x42, 0x1d, 0x32, 0x86, 0x10, 0x77, 0x7d, 0x81, 0x09, 0x23,
	0x65, 0xd9, 0x99, 0x4e, 0x95, 0xc2, 0x83, 0x8d, 0x17, 0xf1, 0x06, 0x26, 0x1c, 0xc1, 0x95, 0xcb,
	0x59, 0x7a, 0x02, 0x35, 0xec, 0xbc, 0x85, 0xa9, 0x2a, 0x7a, 0x12, 0xe2, 0x24, 0xdd, 0xbd, 0xab,
	0xc0, 0xfb, 0xbe, 0xf7, 0xbf, 0xd7, 0xd5, 0x0d, 0x9d, 0xc5, 0x7a, 0x39, 0xc7, 0xd4, 0xe8, 0xe8,
	0xd3, 0xd2, 0xa0, 0xe1, 0x27, 0x28, 0x57, 0xb8, 0x8a, 0xae, 0x53, 0x7c, 0xff, 0x51, 0xea, 0x55,
	0xaa, 0xaf, 0x7b, 0x7d, 0x65, 0x8c, 0xca, 0xe4, 0xc8, 0x15, 0x5c, 0xad, 0x3f, 0x8c, 0x0e, 0x91,
	0xde, 0xc3, 0xcd, 0x3c, 0x4b, 0x17, 0x73, 0x94, 0xa3, 0xfc, 0xb0, 0xff, 0xa3, 0xab, 0x8c, 0x32,
	0xee, 0x38, 0xb2, 0x27, 0xff, 0xeb, 0xe0, 0x1b, 0x00, 0xbb, 0xd8, 0x1b, 0xf8, 0x13, 0xa8, 0x6b,
	0xa3, 0xa5, 0x20, 0x8f, 0xc8, 0xe3, 0x56, 0x7c, 0x1a, 0xf9, 0x56, 0x51, 0xde, 0x2a, 0xca, 0x0b,
	0x13, 0x57, 0xc6, 0x9f, 0x03, 0xcd, 0x50, 0xd0, 0x82, 0xe2, 0x49, 0xfb, 0xfb, 0xdf, 0x1f, 0xb5,
	0xc6, 0x96, 0xd4, 0x7b, 0x94, 0x05, 0x09, 0xcd, 0x90, 0xbf, 0x80, 0x5a, 0x86, 0x52, 0xd4, 0x4a,
	0x93, 0x03, 0x4b, 0x5a, 0xc6, 0xf6, 0x54, 0x28, 0xea, 0xa5, 0xc9, 0xa1, 0xeb, 0xa9, 0x5c, 0x4f,
	0x85, 0x52, 0x04, 0xa5, 0xc9, 0xd8, 0xf5, 0x54, 0x28, 0xf9, 0x1b, 0x08, 0x32, 0xbc, 0x54, 0x28,
	0xc2, 0x22, 0xf8, 0xd8, 0xc2, 0xad, 0x2d, 0x61, 0x3d, 0xca, 0x8e, 0x86, 0x94, 0x41, 0x52, 0xcf,
	0x70, 0x8a, 0x7c, 0x02, 0xa1, 0x33, 0x48, 0xd1, 0xa8, 0xa4, 0x88, 0xad, 0x22, 0xb0, 0x0a, 0xe9,
	0x1d, 0xd2, 0xc6, 0x60, 0xa5, 0x1d, 0x83, 0x3c, 0x46, 0x90, 0xa1, 0x9c, 0x22, 0xbf, 0x80, 0x86,
	0x77, 0x48, 0xd1, 0xac, 0x24, 0x71, 0x41, 0x42, 0x27, 0x91, 0x7c, 0x0a, 0x4d, 0x37, 0xcd, 0x65,
	0xaa, 0x37, 0x02, 0xaa, 0x0c, 0xd4, 0x1d, 0x52, 0x76, 0x9a, 0x34, 0xec, 0x40, 0x33, 0xbd, 0xe1,
	0x33, 0x00, 0xbf, 0x16, 0x67, 0x6a, 0x55, 0x32, 0xc5, 0xd6, 0xc4, 0xdc, 0x6a, 0x6e, 0x55, 0x32,
	0x0f, 0xd5, 0xae, 0x32, 0x9c, 0x0f, 0xc5, 0xdc, 0x70, 0x56, 0xf5, 0x0e, 0x5a, 0xfb, 0x25, 0x39,
	0xd7, 0xfd, 0x4a, 0x2e, 0x17, 0xab, 0xe9, 0x17, 0x65, 0x65, 0xe7, 0xc0, 0x96, 0xf2, 0xf3, 0x3a,
	0x5d, 0xca, 0x85, 0xe8, 0x14, 0x99, 0xc0, 0x9a, 0x82, 0x2d, 0xa1, 0x8c, 0x24, 0xb7, 0x98, 0xbd,
	0xf2, 0xa9, 0x16, 0x47, 0xa5, 0x2f, 0xee, 0x4b, 0xca, 0xbe, 0x24, 0x34, 0xd5, 0xfc, 0x15, 0x84,
	0xda, 0xd8, 0x85, 0x88, 0xe3, 0xd2, 0xf0, 0xc4, 0xc2, 0x81, 0x36, 0x38, 0xd3, 0xfc, 0x1c, 0x02,
	0xfb, 0xa5, 0x78, 0x2a, 0x4e, 0x0a, 0x57, 0xf0, 0xf5, 0xf7, 0x19, 0x39, 0x78, 0xcd, 0x3d, 0x99,
	0x2b, 0x62, 0xc1, 0x0b, 0x15, 0x37, 0xbf, 0xce, 0xee, 0xfd, 0xaf, 0x88, 0xf9, 0x5b, 0xaf, 0x18,
	0x8b, 0x07, 0x45, 0x8a, 0xae, 0x55, 0xdc, 0x9d, 0x64, 0xcc, 0x5f, 0x7b, 0xcd, 0x33, 0xd1, 0x2d,
	0xd2, 0x74, 0xf2, 0x24, 0xfb, 0x27, 0xe1, 0xb9, 0x49, 0xfb, 0x66, 0xd7, 0x27, 0x3f, 0x77, 0x7d,
	0xf2, 0x67, 0xd7, 0x27, 0x57, 0xa1, 0xe3, 0xc6, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x94, 0xe3,
	0x29, 0xa4, 0xb2, 0x05, 0x00, 0x00,
}
