// Code generated by protoc-gen-validate
// source: enum.proto
// DO NOT EDIT!!!

package tests_kitchensink

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/gogo/protobuf/types"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)

	_ = types.DynamicAny{}
)

// Validate checks the field values on Enum with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Enum) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for None

	if m.GetConst() != 3 {
		return EnumValidationError{
			Field:  "Const",
			Reason: "value must equal 3",
		}
	}

	if _, ok := MyEnum_name[int32(m.GetDefinedOnly())]; !ok {
		return EnumValidationError{
			Field:  "DefinedOnly",
			Reason: "value must be one of the defined enum values",
		}
	}

	if _, ok := _Enum_In_InLookup[m.GetIn()]; !ok {
		return EnumValidationError{
			Field:  "In",
			Reason: "value must be in list [0 1 3]",
		}
	}

	if _, ok := _Enum_NotIn_NotInLookup[m.GetNotIn()]; ok {
		return EnumValidationError{
			Field:  "NotIn",
			Reason: "value must not be in list [2 4]",
		}
	}

	return nil
}

// EnumValidationError is the validation error returned by Enum.Validate if the
// designated constraints aren't met.
type EnumValidationError struct {
	Field  string
	Reason string
	Cause  error
	Key    bool
}

// Error satisfies the builtin error interface
func (e EnumValidationError) Error() string {
	cause := ""
	if e.Cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.Cause)
	}

	key := ""
	if e.Key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEnum.%s: %s%s",
		key,
		e.Field,
		e.Reason,
		cause)
}

var _ error = EnumValidationError{}

var _Enum_In_InLookup = map[MyEnum]struct{}{
	0: {},
	1: {},
	3: {},
}

var _Enum_NotIn_NotInLookup = map[MyEnum]struct{}{
	2: {},
	4: {},
}
