// Code generated by protoc-gen-validate
// source: message.proto
// DO NOT EDIT!!!

package tests_kitchensink

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/gogo/protobuf/types"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)

	_ = types.DynamicAny{}
)

// Validate checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Message) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetNone()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MessageValidationError{
				Field:  "None",
				Reason: "embedded message failed validation",
				Cause:  err,
			}
		}
	}

	if m.GetRequired() == nil {
		return MessageValidationError{
			Field:  "Required",
			Reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetRequired()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MessageValidationError{
				Field:  "Required",
				Reason: "embedded message failed validation",
				Cause:  err,
			}
		}
	}

	// skipping validation for skip

	return nil
}

// MessageValidationError is the validation error returned by Message.Validate
// if the designated constraints aren't met.
type MessageValidationError struct {
	Field  string
	Reason string
	Cause  error
	Key    bool
}

// Error satisfies the builtin error interface
func (e MessageValidationError) Error() string {
	cause := ""
	if e.Cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.Cause)
	}

	key := ""
	if e.Key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessage.%s: %s%s",
		key,
		e.Field,
		e.Reason,
		cause)
}

var _ error = MessageValidationError{}

// Validate checks the field values on Message_Embed with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *Message_Embed) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// Message_EmbedValidationError is the validation error returned by
// Message_Embed.Validate if the designated constraints aren't met.
type Message_EmbedValidationError struct {
	Field  string
	Reason string
	Cause  error
	Key    bool
}

// Error satisfies the builtin error interface
func (e Message_EmbedValidationError) Error() string {
	cause := ""
	if e.Cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.Cause)
	}

	key := ""
	if e.Key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessage_Embed.%s: %s%s",
		key,
		e.Field,
		e.Reason,
		cause)
}

var _ error = Message_EmbedValidationError{}
