// Code generated by protoc-gen-gogo.
// source: oneof.proto
// DO NOT EDIT!

package tests_kitchensink

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/lyft/protoc-gen-validate/validate"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type OneOf_Enum int32

const (
	OneOf_DEFAULT OneOf_Enum = 0
)

var OneOf_Enum_name = map[int32]string{
	0: "DEFAULT",
}
var OneOf_Enum_value = map[string]int32{
	"DEFAULT": 0,
}

func (x OneOf_Enum) String() string {
	return proto.EnumName(OneOf_Enum_name, int32(x))
}
func (OneOf_Enum) EnumDescriptor() ([]byte, []int) { return fileDescriptorOneof, []int{0, 0} }

type OneOf struct {
	// Types that are valid to be assigned to None:
	//	*OneOf_String_
	//	*OneOf_MsgNone
	None isOneOf_None `protobuf_oneof:"none"`
	// Types that are valid to be assigned to Required:
	//	*OneOf_Bytes
	//	*OneOf_MsgReq
	//	*OneOf_Enum_
	//	*OneOf_Embed_
	//	*OneOf_OtherEmbed_
	Required isOneOf_Required `protobuf_oneof:"required"`
}

func (m *OneOf) Reset()                    { *m = OneOf{} }
func (m *OneOf) String() string            { return proto.CompactTextString(m) }
func (*OneOf) ProtoMessage()               {}
func (*OneOf) Descriptor() ([]byte, []int) { return fileDescriptorOneof, []int{0} }

type isOneOf_None interface {
	isOneOf_None()
}
type isOneOf_Required interface {
	isOneOf_Required()
}

type OneOf_String_ struct {
	String_ string `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}
type OneOf_MsgNone struct {
	MsgNone *OneOf_Embed `protobuf:"bytes,2,opt,name=msg_none,json=msgNone,oneof"`
}
type OneOf_Bytes struct {
	Bytes []byte `protobuf:"bytes,3,opt,name=bytes,proto3,oneof"`
}
type OneOf_MsgReq struct {
	MsgReq *OneOf_Embed `protobuf:"bytes,4,opt,name=msg_req,json=msgReq,oneof"`
}
type OneOf_Enum_ struct {
	Enum OneOf_Enum `protobuf:"varint,5,opt,name=enum,proto3,enum=tests.kitchensink.OneOf_Enum,oneof"`
}
type OneOf_Embed_ struct {
	Embed *OneOf_Embed `protobuf:"bytes,6,opt,name=embed,oneof"`
}
type OneOf_OtherEmbed_ struct {
	OtherEmbed string `protobuf:"bytes,7,opt,name=other_embed,json=otherEmbed,proto3,oneof"`
}

func (*OneOf_String_) isOneOf_None()         {}
func (*OneOf_MsgNone) isOneOf_None()         {}
func (*OneOf_Bytes) isOneOf_Required()       {}
func (*OneOf_MsgReq) isOneOf_Required()      {}
func (*OneOf_Enum_) isOneOf_Required()       {}
func (*OneOf_Embed_) isOneOf_Required()      {}
func (*OneOf_OtherEmbed_) isOneOf_Required() {}

func (m *OneOf) GetNone() isOneOf_None {
	if m != nil {
		return m.None
	}
	return nil
}
func (m *OneOf) GetRequired() isOneOf_Required {
	if m != nil {
		return m.Required
	}
	return nil
}

func (m *OneOf) GetString_() string {
	if x, ok := m.GetNone().(*OneOf_String_); ok {
		return x.String_
	}
	return ""
}

func (m *OneOf) GetMsgNone() *OneOf_Embed {
	if x, ok := m.GetNone().(*OneOf_MsgNone); ok {
		return x.MsgNone
	}
	return nil
}

func (m *OneOf) GetBytes() []byte {
	if x, ok := m.GetRequired().(*OneOf_Bytes); ok {
		return x.Bytes
	}
	return nil
}

func (m *OneOf) GetMsgReq() *OneOf_Embed {
	if x, ok := m.GetRequired().(*OneOf_MsgReq); ok {
		return x.MsgReq
	}
	return nil
}

func (m *OneOf) GetEnum() OneOf_Enum {
	if x, ok := m.GetRequired().(*OneOf_Enum_); ok {
		return x.Enum
	}
	return OneOf_DEFAULT
}

func (m *OneOf) GetEmbed() *OneOf_Embed {
	if x, ok := m.GetRequired().(*OneOf_Embed_); ok {
		return x.Embed
	}
	return nil
}

func (m *OneOf) GetOtherEmbed() string {
	if x, ok := m.GetRequired().(*OneOf_OtherEmbed_); ok {
		return x.OtherEmbed
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*OneOf) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _OneOf_OneofMarshaler, _OneOf_OneofUnmarshaler, _OneOf_OneofSizer, []interface{}{
		(*OneOf_String_)(nil),
		(*OneOf_MsgNone)(nil),
		(*OneOf_Bytes)(nil),
		(*OneOf_MsgReq)(nil),
		(*OneOf_Enum_)(nil),
		(*OneOf_Embed_)(nil),
		(*OneOf_OtherEmbed_)(nil),
	}
}

func _OneOf_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*OneOf)
	// none
	switch x := m.None.(type) {
	case *OneOf_String_:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.String_)
	case *OneOf_MsgNone:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MsgNone); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("OneOf.None has unexpected type %T", x)
	}
	// required
	switch x := m.Required.(type) {
	case *OneOf_Bytes:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		_ = b.EncodeRawBytes(x.Bytes)
	case *OneOf_MsgReq:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MsgReq); err != nil {
			return err
		}
	case *OneOf_Enum_:
		_ = b.EncodeVarint(5<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.Enum))
	case *OneOf_Embed_:
		_ = b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Embed); err != nil {
			return err
		}
	case *OneOf_OtherEmbed_:
		_ = b.EncodeVarint(7<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.OtherEmbed)
	case nil:
	default:
		return fmt.Errorf("OneOf.Required has unexpected type %T", x)
	}
	return nil
}

func _OneOf_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*OneOf)
	switch tag {
	case 1: // none.string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.None = &OneOf_String_{x}
		return true, err
	case 2: // none.msg_none
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OneOf_Embed)
		err := b.DecodeMessage(msg)
		m.None = &OneOf_MsgNone{msg}
		return true, err
	case 3: // required.bytes
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Required = &OneOf_Bytes{x}
		return true, err
	case 4: // required.msg_req
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OneOf_Embed)
		err := b.DecodeMessage(msg)
		m.Required = &OneOf_MsgReq{msg}
		return true, err
	case 5: // required.enum
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Required = &OneOf_Enum_{OneOf_Enum(x)}
		return true, err
	case 6: // required.embed
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OneOf_Embed)
		err := b.DecodeMessage(msg)
		m.Required = &OneOf_Embed_{msg}
		return true, err
	case 7: // required.other_embed
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Required = &OneOf_OtherEmbed_{x}
		return true, err
	default:
		return false, nil
	}
}

func _OneOf_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*OneOf)
	// none
	switch x := m.None.(type) {
	case *OneOf_String_:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.String_)))
		n += len(x.String_)
	case *OneOf_MsgNone:
		s := proto.Size(x.MsgNone)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// required
	switch x := m.Required.(type) {
	case *OneOf_Bytes:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Bytes)))
		n += len(x.Bytes)
	case *OneOf_MsgReq:
		s := proto.Size(x.MsgReq)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *OneOf_Enum_:
		n += proto.SizeVarint(5<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Enum))
	case *OneOf_Embed_:
		s := proto.Size(x.Embed)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *OneOf_OtherEmbed_:
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.OtherEmbed)))
		n += len(x.OtherEmbed)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type OneOf_Embed struct {
}

func (m *OneOf_Embed) Reset()                    { *m = OneOf_Embed{} }
func (m *OneOf_Embed) String() string            { return proto.CompactTextString(m) }
func (*OneOf_Embed) ProtoMessage()               {}
func (*OneOf_Embed) Descriptor() ([]byte, []int) { return fileDescriptorOneof, []int{0, 0} }

type OneOf_OtherEmbed struct {
}

func (m *OneOf_OtherEmbed) Reset()                    { *m = OneOf_OtherEmbed{} }
func (m *OneOf_OtherEmbed) String() string            { return proto.CompactTextString(m) }
func (*OneOf_OtherEmbed) ProtoMessage()               {}
func (*OneOf_OtherEmbed) Descriptor() ([]byte, []int) { return fileDescriptorOneof, []int{0, 1} }

func init() {
	proto.RegisterType((*OneOf)(nil), "tests.kitchensink.OneOf")
	proto.RegisterType((*OneOf_Embed)(nil), "tests.kitchensink.OneOf.Embed")
	proto.RegisterType((*OneOf_OtherEmbed)(nil), "tests.kitchensink.OneOf.OtherEmbed")
	proto.RegisterEnum("tests.kitchensink.OneOf_Enum", OneOf_Enum_name, OneOf_Enum_value)
}

func init() { proto.RegisterFile("oneof.proto", fileDescriptorOneof) }

var fileDescriptorOneof = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0x80, 0xbb, 0x4d, 0x36, 0x69, 0x27, 0xe5, 0xa7, 0xdd, 0x1f, 0x34, 0x14, 0x94, 0x58, 0x2f,
	0x39, 0x45, 0xa8, 0xe0, 0xc5, 0x83, 0x18, 0xac, 0xe4, 0x20, 0x16, 0x16, 0x3d, 0x97, 0xd6, 0x4e,
	0xd3, 0x50, 0xb3, 0x6b, 0x77, 0xb7, 0x82, 0x57, 0x8f, 0xbe, 0x8a, 0x2f, 0x20, 0x9e, 0xfa, 0x3a,
	0x7d, 0x0b, 0x49, 0x52, 0xbd, 0x88, 0xd0, 0xdb, 0xec, 0xec, 0x37, 0xdf, 0xce, 0xce, 0x80, 0x27,
	0x05, 0xca, 0x59, 0xf4, 0xa4, 0xa4, 0x91, 0xac, 0x63, 0x50, 0x1b, 0x1d, 0x2d, 0x32, 0xf3, 0x30,
	0x47, 0xa1, 0x33, 0xb1, 0xe8, 0xee, 0x3f, 0x8f, 0x1f, 0xb3, 0xe9, 0xd8, 0xe0, 0xc9, 0x77, 0x50,
	0xb1, 0xbd, 0x77, 0x0b, 0xe8, 0x50, 0xe0, 0x70, 0xc6, 0x8e, 0xc1, 0xd1, 0x46, 0x65, 0x22, 0xf5,
	0x49, 0x40, 0xc2, 0x66, 0xdc, 0xfc, 0xdc, 0xac, 0x2d, 0x5b, 0xd5, 0xdb, 0x34, 0xa9, 0xf1, 0xed,
	0x15, 0x3b, 0x87, 0x46, 0xae, 0xd3, 0x91, 0x90, 0x02, 0xfd, 0x7a, 0x40, 0x42, 0xaf, 0x7f, 0x18,
	0xfd, 0x7a, 0x2d, 0x2a, 0x85, 0xd1, 0x20, 0x9f, 0xe0, 0x34, 0xa9, 0x71, 0x37, 0xd7, 0xe9, 0xad,
	0x14, 0xc8, 0xf6, 0x80, 0x4e, 0x5e, 0x0c, 0x6a, 0xdf, 0x0a, 0x48, 0xd8, 0x4a, 0x08, 0xaf, 0x8e,
	0x6c, 0x00, 0x05, 0x32, 0x52, 0xb8, 0xf4, 0xed, 0x5d, 0x9c, 0x31, 0x14, 0xad, 0xd1, 0x37, 0x52,
	0x6f, 0x93, 0x84, 0x70, 0x27, 0xd7, 0x29, 0xc7, 0x25, 0xbb, 0x00, 0x1b, 0xc5, 0x2a, 0xf7, 0x69,
	0x40, 0xc2, 0x7f, 0xfd, 0x83, 0xbf, 0x1d, 0x62, 0x95, 0x6f, 0x15, 0xaf, 0x5b, 0x45, 0x59, 0xc8,
	0xce, 0x80, 0x62, 0xe1, 0xf7, 0x9d, 0x9d, 0x7e, 0x46, 0x78, 0x85, 0xb3, 0x23, 0xf0, 0xa4, 0x99,
	0xa3, 0x1a, 0x55, 0xd5, 0x6e, 0x31, 0xbe, 0x84, 0x70, 0x28, 0x93, 0x25, 0xdb, 0x75, 0x81, 0x56,
	0x41, 0x0b, 0x60, 0xf8, 0x93, 0xee, 0xfd, 0x07, 0xbb, 0xe8, 0x86, 0x79, 0xe0, 0x5e, 0x0d, 0xae,
	0x2f, 0xef, 0x6f, 0xee, 0xda, 0xb5, 0xd8, 0x01, 0xbb, 0x98, 0x6f, 0xdc, 0x81, 0x86, 0xc2, 0xe5,
	0x2a, 0x53, 0x38, 0x65, 0xf4, 0x63, 0xb3, 0xb6, 0xc8, 0xc4, 0x29, 0x97, 0x76, 0xfa, 0x15, 0x00,
	0x00, 0xff, 0xff, 0x4b, 0x10, 0x63, 0x00, 0xef, 0x01, 0x00, 0x00,
}
