package php

const fileTpl = 
`
<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: {{ .File.InputPath }}

namespace {{ phpPackage .File }};

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Mapping\ClassMetadata;
{{ if isOfFileType . }}
class Person extends \Google\Protobuf\Internal\Message
{
	{{ range .AllMessages -}}
	{{- template "msg" . -}}
	{{- end }}
}
{{ end }}
`
