package dotnet

const fileTpl = `// <auto-generated>
//     Code generated by protoc-gen-validate.  DO NOT EDIT!
//     source: {{ .InputPath }}
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Text;

namespace {{ namespace . }}
{
{{ range .AllMessages }}
	{{ template "msg" . }}
{{ end }}
}
`
