package java

const fileTpl = `// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: {{ .InputPath }}

package {{ javaPackage . }};

public class {{ classNameFile . }}Validator {
	private static boolean initialized = false;
	public static void registerAllValidators() {
		// Flips a bit to force this class to be initialized, which ensures that
		// the static block below is executed.
		initialized = true;
	}

	static {
		{{ range .AllMessages }}
		com.lyft.pgv.GeneratedValidatorIndex.registerValidator(
			{{ qualifiedName . }}.class,
			new {{ simpleName .}}Validator()
		);
		{{- end }}
	}

{{ range .AllMessages -}}
	{{- template "msg" . -}}
{{- end }}
}
`
