package java

const fileIndexTpl = `// Code generated by protoc-gen-validate. DO NOT EDIT.

package com.lyft.pgv;

public final class ValidatorIndex {
	private ValidatorIndex() { }

	private static final java.util.Map<java.lang.Class, com.lyft.pgv.Validator> INDEX = new java.util.HashMap<>();

	static {
		{{ range . -}}{{- $file := . -}}
		{{- range .AllMessages -}}{{- $message := . -}}
		INDEX.put({{ qualifiedName $message }}.class, new {{javaPackage $file}}.{{ classNameFile $file }}Validator.{{ simpleName $message }}Validator());
		{{ end -}}{{ end }}
	}

	private static final Validator<Object> ALWAYS_VALID = new Validator<Object>() {
		@Override
		public void assertValid(Object proto) throws ValidationException {
			// Do nothing. Always valid.
		}
	};

	public static <T> com.lyft.pgv.Validator<T> validatorFor(java.lang.Class<T> clazz) {
		return INDEX.getOrDefault(clazz, ALWAYS_VALID);
	}
}`
