package java

const fileIndexTpl = `// Code generated by protoc-gen-validate. DO NOT EDIT.

package com.lyft.pgv;

public final class GeneratedValidatorIndex implements com.lyft.pgv.ValidatorIndex {
	private GeneratedValidatorIndex() { }

	public static final GeneratedValidatorIndex INSTANCE = new GeneratedValidatorIndex();

	private static final java.util.Map<java.lang.Class, com.lyft.pgv.Validator> VALIDATOR_INDEX = new java.util.HashMap<>();

	static {
		{{ range . -}}{{- $file := . -}}{{- if importsPvg $file }}
		{{- range .AllMessages -}}{{- $message := . -}}
		VALIDATOR_INDEX.put({{ qualifiedName $message }}.class, new {{javaPackage $file}}.{{ classNameFile $file }}Validator.{{ simpleName $message }}Validator());
		{{ end -}}{{- end -}}{{- end }}
	}

	private static final Validator<Object> ALWAYS_VALID = new Validator<Object>() {
		@Override
		public void assertValid(Object proto) throws ValidationException {
			// Do nothing. Always valid.
		}
	};

	@SuppressWarnings("unchecked")
	public <T> com.lyft.pgv.Validator<T> validatorFor(java.lang.Class clazz) {
		return VALIDATOR_INDEX.getOrDefault(clazz, ALWAYS_VALID);
	}

	@SuppressWarnings("unchecked")
	public static <T> com.lyft.pgv.Validator<T> validatorFor(Object instance) {
		return INSTANCE.validatorFor(instance == null ? null : instance.getClass());
	}
}`
