cc_binary(
    name = "cc-harness",
    srcs = ["harness.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//tests/harness:harness_proto",
        "//tests/harness/cases:cc",
    ],
)
