package php_yaml

const fileTpl = `# Generated by protoc-gen-validate.  DO NOT EDIT!
# source: {{ .File.InputPath }}
{{- if isOfFileType . }}
{{ range .AllMessages -}}
  {{- template "msg" . -}}
{{- end }}
{{ end }}
`
