load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "internal",
    srcs = [
        "internal.go",
    ],
    importpath = "github.com/envoyproxy/protoc-gen-validate/internal",
    visibility = ["//visibility:public"],
    deps = [],
)
