package golang

const fileTpl = `// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: {{ .InputPath }}

{{ $ThisPkgName := pkg . }}

package {{ $ThisPkgName }}

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	{{ range $pkg, $enum := enumPackages (externalEnums .) }}
		{{ if ne $pkg $ThisPkgName }}
			{{ $pkg }} "{{ $enum.FilePath }}"
		{{ end }}
	{{ end }}
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	{{ range $pkg, $enum := enumPackages (externalEnums .) }}
	{{ if ne $pkg $ThisPkgName }}
	_ = {{ $pkg }}.{{ $enum.Name }}(0)
	{{ else }}
	_ = {{ $enum.Name }}(0)
	{{ end }}
	{{ end }}
)

{{- if fileneeds . "uuid" }}
// define the regex for a UUID once up-front
var _{{ snakeCase .File.InputPath.BaseName }}_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")
{{ end }}

{{ range .AllMessages }}
	{{ template "msg" . }}
{{ end }}
`
