name: Bump version
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      prerelease:
        type: boolean
        description: Pre-release?
        default: true
      bump:
        type: choice
        description: Which version?
        default: 'minor'
        options:
          - minor
          - patch

env:
  PRERELEASE: ${{github.event.inputs.prerelease}}
  DEFAULT_BUMP: ${{github.event.inputs.bump}}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g semver
      - name: Bump version and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/actions/github-tag-action/entrypoint.sh
