name: Bump version
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        description: Remove SNAPSHOT?

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - if: ${{ github.event.inputs.release == false }}
        run: echo "PRERELEASE=true" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g semver
      - name: Bump version and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: "minor"
          PRERELEASE_SUFFIX: "SNAPSHOT"
        run: .github/actions/github-tag-action/entrypoint.sh
